export const BARANGAY_OPTIONS = [
  'All Barangays',
  'Burol I',
  'Burol II',
  'Burol III',
  'Emmanuel Bergado I',
  'Emmanuel Bergado II',
  'Fatima I',
  'Fatima II',
  'Fatima III',
  'Luzviminda I',
  'Luzviminda II',
  'San Andres I',
  'San Andres II',
  'San Antonio de Padua I',
  'San Antonio de Padua II',
  'San Francisco I',
  'San Francisco II',
  'San Lorenzo Ruiz I',
  'San Lorenzo Ruiz II',
  'San Luis I',
  'San Luis II',
  'San Mateo',
  'San Nicolas I',
  'San Nicolas II',
  'San Roque (Sta. Cristina II)',
  'San Simon (Barangay 7)',
  'Santa Cristina I',
  'Santa Cristina II',
  'Santa Cruz I',
  'Santa Cruz II',
  'Santa Fe',
  'Santa Maria (Barangay 20)',
  'Victoria Reyes',
] as const;